appVersion: app/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:                   # Pod specification
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80 
        resources:          # Resource requests and limits for the container 
          requests:         # Minimum resources required [minimum resources allowed to the per container]
            cpu: "100m"     # 100 millicores = 0.1 core [1core = 1000millicores]
            memory: "128Mi" # 128 Megabytes of ram [1Gi = 1024Mi]
          limits:           # Maximum resources allowed for per container
            cpu: "500m"     # 500 millicores = 0.5 core
            memory: "512Mi" # 512 Megabytes of ram