apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ostad
  labels:
    app: nginx
spec:
  type: LoadBalancer               # <-- change from LoadBalancer to NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8088               # Service port inside cluster
      targetPort: 80           # Pod/container port
   












# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
#   namespace: ostad
#   labels:
#     app: nginx

# spec:
#   type: LoadBalancer           # external LB (cloud provider) or use `minikube tunnel`
#   selector:
#     app: nginx

#   ports:
#     - protocol: TCP
#       port: 8080                 # external port on the LoadBalancer/Service
#       targetPort: 80           # Pod/container port
#       # do NOT set nodePort here unless you specifically need it
