apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque   # default type for generic secrets , and we can do everything with the default type . There are many other types like kubernetes.io/basic-auth etc. check the docs for more. 
data:
  username: dXNlcm5hbWU=  #store data in base64 encoded 'username'
  password: cGFzc3dvcmQ=  #store data in base64 encoded 'password' 

# To create this secret using kubectl command line, you can use the following command:
# kubectl create secret generic my-secret --from-literal=username=username --from-literal=password=password
# This command will create a secret named 'my-secret' with the specified username and password.