apiVersion: v2

# Helm chart metadata (name, description, ***type: application, version, appVersion, maintainers) define by user in chart.yaml

name: django-app # Name of the Helm chart
description: A Helm chart for deploying My Application
type: application
version: 1.0.0 # Version of the Helm chart
appVersion: "1.0.0" # Version of the application being deployed
maintainers:
  - name: Jane Doe
    email: 6Dm0k@example.com