# values.yaml : values for the helm chart. we define the values which we want to use in the deployment.yaml file for container related things like image, replica count etc.

replicaCount: 3
image:
  repository: my-django-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80