apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.name" . }}-service
  labels:
    app: {{ include "django-app.name" . }}
spec:
  type: {{ .Values.service.type }} # this .Values.service.type call the values.yaml file and get the value of service.type
  selector:
    app: {{ include "django-app.name" . }}
  ports:
    - port: {{ .Values.service.port }} # this .Values.service.port call the values.yaml file and get the value of service.port
      targetPort: 8000