apiVersion: v1 
kind: Secret
metadata:
  name: {{ include "django-app.name" . }}-secret
  labels:
    app: {{ include "django-app.name" . }}
type: Opaque
data:
  Django_SECRET_KEY: {{ .Values.secrets.Django_SECRET_KEY | b64enc | quote }}
# this .Values.secrets.Django_SECRET_KEY call the values.yaml file and get the value